

{
  "language": "scala",
  "script": [
    "sbt -Ddotty.travis.build=yes update compile test scalastyle"
  ],
  "jdk": "oraclejdk8",
  "before_install": [
    "cd ..",
    "git clone https://github.com/scala/scala.git",
    "cd dotty"
  ],
  "os": "linux"
}

